export type ServiceWindow = {
  days: number[];
  start: string;
  end: string;
};

export type Resource = {
  id: number;
  name: string;
  type: "Food bank" | "Hot meal" | "Community fridge" | "Student support" | "Family support";
  neighborhood: string;
  city: string;
  address: string;
  contact: {
    phone?: string;
    website?: string;
    email?: string;
    note: string;
  };
  fallbackDistanceKm: number;
  tags: string[];
  requirements: string[];
  languages: string[];
  supplies: string[];
  serviceWindows?: ServiceWindow[];
  hoursText?: string;
  source?: "curated" | "openstreetmap";
  geo: {
    lat: number;
    lng: number;
  };
};

const weekday = [1, 2, 3, 4, 5];
const monWedFri = [1, 3, 5];
const tueThu = [2, 4];
const weekend = [6, 0];

export const resources: Resource[] = [
  {
    id: 1,
    name: "Davis Campus Food Shelf",
    type: "Student support",
    neighborhood: "Sheridan Davis",
    city: "Brampton",
    address: "7899 McLaughlin Rd, Brampton",
    contact: {
      website: "https://www.sheridancollege.ca/student-life/student-services",
      note: "Use Sheridan student services or campus support channels for current pantry access.",
    },
    fallbackDistanceKm: 0.8,
    tags: ["student", "groceries", "no-id", "halal", "vegetarian"],
    requirements: ["Student-focused support", "Confirm campus access before visiting"],
    languages: ["English", "Punjabi", "Urdu"],
    supplies: ["Pantry staples", "Rice", "Lentils", "Hygiene kits"],
    serviceWindows: [{ days: weekday, start: "10:00", end: "18:00" }],
    geo: { lat: 43.7302, lng: -79.7325 },
  },
  {
    id: 2,
    name: "Regeneration Outreach",
    type: "Hot meal",
    neighborhood: "Downtown Brampton",
    city: "Brampton",
    address: "156 Main St N, Brampton",
    contact: {
      phone: "905-796-5888",
      website: "https://regenbrampton.com/",
      note: "Call or check the program website before visiting; hours and intake can change.",
    },
    fallbackDistanceKm: 2.4,
    tags: ["hot-meal", "urgent", "no-id", "wheelchair", "vegetarian"],
    requirements: ["Walk-in services may be available", "Confirm service window before visiting"],
    languages: ["English"],
    supplies: ["Hot meals", "Drop-in support", "Community referrals"],
    serviceWindows: [
      { days: weekday, start: "08:30", end: "14:00" },
      { days: [6], start: "10:00", end: "13:00" },
    ],
    geo: { lat: 43.6918, lng: -79.7641 },
  },
  {
    id: 3,
    name: "Food Banks Mississauga",
    type: "Food bank",
    neighborhood: "East Mississauga",
    city: "Mississauga",
    address: "3121 Universal Dr, Mississauga",
    contact: {
      phone: "905-270-5589",
      website: "https://www.foodbanksmississauga.ca/",
      note: "Use their intake and locator tools to confirm the closest pickup option.",
    },
    fallbackDistanceKm: 4.7,
    tags: ["groceries", "family", "delivery", "vegetarian", "newcomer"],
    requirements: ["Use local intake process", "Confirm closest pickup location"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh food referrals", "Family support"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "17:00" }],
    geo: { lat: 43.6379, lng: -79.6416 },
  },
  {
    id: 4,
    name: "Eden Food for Change",
    type: "Food bank",
    neighborhood: "Meadowvale",
    city: "Mississauga",
    address: "3185 Unity Dr, Mississauga",
    contact: {
      phone: "905-785-3651",
      website: "https://edenffc.org/",
      note: "Registration and appointment rules may apply; confirm before visiting.",
    },
    fallbackDistanceKm: 7.8,
    tags: ["groceries", "family", "vegetarian", "newcomer"],
    requirements: ["Registration may be required", "Confirm eligibility before visiting"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh produce", "Community referrals"],
    serviceWindows: [{ days: tueThu, start: "12:00", end: "19:00" }],
    geo: { lat: 43.5787, lng: -79.7575 },
  },
  {
    id: 5,
    name: "Daily Bread Food Bank",
    type: "Food bank",
    neighborhood: "Etobicoke",
    city: "Toronto",
    address: "191 New Toronto St, Toronto",
    contact: {
      phone: "416-203-0050",
      website: "https://www.dailybread.ca/",
      note: "Use Daily Bread's food bank locator for the best current member-agency match.",
    },
    fallbackDistanceKm: 18.1,
    tags: ["groceries", "family", "delivery", "vegetarian", "no-id"],
    requirements: ["Use locator or call ahead", "Bring ID if available, but ask about no-ID options"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh produce", "Member agency referrals"],
    serviceWindows: [{ days: weekday, start: "08:30", end: "16:30" }],
    geo: { lat: 43.6005, lng: -79.5057 },
  },
  {
    id: 6,
    name: "Fort York Food Bank",
    type: "Food bank",
    neighborhood: "Trinity Bellwoods",
    city: "Toronto",
    address: "797 Dundas St W, Toronto",
    contact: {
      phone: "416-203-3011",
      website: "https://fyfb.com/",
      note: "Confirm drop-in and food bank hours before visiting.",
    },
    fallbackDistanceKm: 25.5,
    tags: ["groceries", "hot-meal", "urgent", "no-id", "vegetarian"],
    requirements: ["Walk-in support may be available", "Confirm hours before visiting"],
    languages: ["English"],
    supplies: ["Groceries", "Meals", "Clothing and referrals"],
    serviceWindows: [
      { days: monWedFri, start: "11:00", end: "15:00" },
      { days: [4], start: "16:00", end: "19:00" },
    ],
    geo: { lat: 43.6519, lng: -79.4093 },
  },
  {
    id: 7,
    name: "North York Harvest Food Bank",
    type: "Food bank",
    neighborhood: "Amesbury",
    city: "Toronto",
    address: "116 Industry St, Toronto",
    contact: {
      phone: "416-635-7771",
      website: "https://northyorkharvest.com/",
      note: "Use their network information to confirm the correct agency and catchment area.",
    },
    fallbackDistanceKm: 23.4,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Use agency referral or call ahead", "Service area may apply"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh food", "Community referrals"],
    serviceWindows: [{ days: weekday, start: "09:30", end: "16:00" }],
    geo: { lat: 43.7009, lng: -79.4899 },
  },
  {
    id: 8,
    name: "Feed Scarborough",
    type: "Food bank",
    neighborhood: "Scarborough",
    city: "Toronto",
    address: "Scarborough, Toronto",
    contact: {
      website: "https://www.feedscarborough.ca/",
      note: "Feed Scarborough operates multiple programs; check the site for the exact location.",
    },
    fallbackDistanceKm: 42.2,
    tags: ["groceries", "family", "halal", "vegetarian", "newcomer"],
    requirements: ["Confirm nearest program location", "Service times vary by site"],
    languages: ["English"],
    supplies: ["Groceries", "Culturally appropriate food", "Prepared meals"],
    serviceWindows: [
      { days: weekday, start: "10:00", end: "17:00" },
      { days: weekend, start: "11:00", end: "14:00" },
    ],
    geo: { lat: 43.7764, lng: -79.2318 },
  },
  {
    id: 9,
    name: "Richmond Hill Community Food Bank",
    type: "Food bank",
    neighborhood: "Richmond Hill",
    city: "Richmond Hill",
    address: "55 Newkirk Rd, Richmond Hill",
    contact: {
      phone: "905-508-4761",
      website: "https://richmondhillcommunityfoodbank.ca/",
      note: "Confirm registration and pickup details before visiting.",
    },
    fallbackDistanceKm: 36.9,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Registration may be required", "Confirm catchment area"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh produce", "Household staples"],
    serviceWindows: [{ days: tueThu, start: "10:00", end: "15:00" }],
    geo: { lat: 43.8752, lng: -79.4232 },
  },
  {
    id: 10,
    name: "Vaughan Food Bank",
    type: "Food bank",
    neighborhood: "Concord",
    city: "Vaughan",
    address: "71 Marycroft Ave, Vaughan",
    contact: {
      phone: "905-851-2333",
      website: "https://vaughanfoodbank.ca/",
      note: "Call ahead for current pickup process and service area details.",
    },
    fallbackDistanceKm: 29.6,
    tags: ["groceries", "family", "vegetarian"],
    requirements: ["Call ahead for current pickup process", "Service area may apply"],
    languages: ["English"],
    supplies: ["Groceries", "Family hampers", "Community referrals"],
    serviceWindows: [{ days: monWedFri, start: "09:00", end: "13:00" }],
    geo: { lat: 43.7856, lng: -79.5617 },
  },
  {
    id: 11,
    name: "The Stop Community Food Centre",
    type: "Hot meal",
    neighborhood: "Davenport",
    city: "Toronto",
    address: "1884 Davenport Rd, Toronto",
    contact: {
      phone: "416-652-7867",
      website: "https://www.thestop.org/",
      note: "Check current drop-in, meal, and food access program schedules.",
    },
    fallbackDistanceKm: 27.5,
    tags: ["hot-meal", "urgent", "no-id", "vegetarian"],
    requirements: ["Drop-in programs may be available", "Confirm schedule before visiting"],
    languages: ["English"],
    supplies: ["Meals", "Community kitchen", "Food access referrals"],
    serviceWindows: [
      { days: weekday, start: "09:00", end: "15:00" },
      { days: [2, 4], start: "16:00", end: "18:30" },
    ],
    geo: { lat: 43.6716, lng: -79.4521 },
  },
  {
    id: 12,
    name: "Feed the Need in Durham",
    type: "Food bank",
    neighborhood: "Oshawa",
    city: "Durham Region",
    address: "371 Marwood Dr, Oshawa",
    contact: {
      phone: "905-571-3863",
      website: "https://feedtheneedindurham.ca/",
      note: "Use partner agency information to confirm the nearest Durham pickup site.",
    },
    fallbackDistanceKm: 71.2,
    tags: ["groceries", "family", "delivery", "vegetarian"],
    requirements: ["Use partner agency intake", "Confirm nearest Durham pickup site"],
    languages: ["English"],
    supplies: ["Groceries", "Regional partner referrals", "Family hampers"],
    serviceWindows: [{ days: weekday, start: "08:00", end: "16:00" }],
    geo: { lat: 43.8792, lng: -78.8795 },
  },
  {
    id: 13,
    name: "Seva Food Bank Malton",
    type: "Food bank",
    neighborhood: "Malton",
    city: "Mississauga",
    address: "2832 Slough St, Mississauga",
    contact: {
      phone: "905-361-7382",
      website: "https://sevafoodbank.com/get-food/",
      note: "Use Seva Food Bank intake information to confirm catchment, registration, and hours.",
    },
    fallbackDistanceKm: 10.2,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Catchment or referral rules may apply", "Confirm current pickup process"],
    languages: ["English", "Punjabi", "Hindi", "Urdu"],
    supplies: ["Groceries", "Fresh food", "Culturally appropriate staples"],
    serviceWindows: [{ days: weekday, start: "10:00", end: "16:00" }],
    geo: { lat: 43.7115, lng: -79.6411 },
  },
  {
    id: 14,
    name: "Seva Food Bank Wolfedale",
    type: "Food bank",
    neighborhood: "Cooksville",
    city: "Mississauga",
    address: "3413 Wolfedale Rd, Mississauga",
    contact: {
      phone: "905-361-7382",
      website: "https://sevafoodbank.com/get-food/",
      note: "Confirm registration, catchment, and current service hours before visiting.",
    },
    fallbackDistanceKm: 13.6,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Registration may be required", "Confirm current hours"],
    languages: ["English", "Punjabi", "Hindi", "Urdu"],
    supplies: ["Groceries", "Fresh food", "Family hampers"],
    serviceWindows: [{ days: weekday, start: "10:00", end: "16:00" }],
    geo: { lat: 43.5664, lng: -79.6386 },
  },
  {
    id: 15,
    name: "Sai Dham Food Bank",
    type: "Food bank",
    neighborhood: "Malton",
    city: "Mississauga",
    address: "7140 Goreway Dr, Mississauga",
    contact: {
      phone: "437-988-4422",
      website: "https://saidhamfoodbank.com/",
      note: "Confirm program availability and distribution schedule for the listed location before visiting.",
    },
    fallbackDistanceKm: 9.4,
    tags: ["groceries", "family", "vegetarian", "delivery"],
    requirements: ["Confirm intake and delivery eligibility", "Service schedule can vary by program"],
    languages: ["English", "Hindi", "Punjabi"],
    supplies: ["Groceries", "Senior support", "Community referrals"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "17:00" }],
    geo: { lat: 43.7234, lng: -79.6354 },
  },
  {
    id: 16,
    name: "St Mary's Food Bank Streetsville",
    type: "Food bank",
    neighborhood: "Streetsville",
    city: "Mississauga",
    address: "Streetsville, Mississauga",
    contact: {
      website: "https://stmarysfoodbank.ca/",
      note: "St Mary's operates multiple Mississauga supports; confirm the correct location and postal-code service area.",
    },
    fallbackDistanceKm: 9.9,
    tags: ["groceries", "family", "delivery", "vegetarian"],
    requirements: ["Postal-code service area may apply", "Confirm location and hours before visiting"],
    languages: ["English"],
    supplies: ["Groceries", "Meals on Wheels referrals", "Family support"],
    serviceWindows: [{ days: weekday, start: "10:00", end: "15:00" }],
    geo: { lat: 43.5823, lng: -79.7117 },
  },
  {
    id: 17,
    name: "Salvation Army Mississauga Food Bank",
    type: "Food bank",
    neighborhood: "Mississauga",
    city: "Mississauga",
    address: "Mississauga",
    contact: {
      website: "https://www.samississauga.com/community-services/food-bank",
      note: "The Salvation Army lists multiple Mississauga food bank locations; apply or confirm the closest location before visiting.",
    },
    fallbackDistanceKm: 15.3,
    tags: ["groceries", "family", "newcomer"],
    requirements: ["Application or intake may be required", "Confirm which Mississauga location fits"],
    languages: ["English"],
    supplies: ["Groceries", "Family support", "Community services"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "16:00" }],
    geo: { lat: 43.589, lng: -79.6441 },
  },
  {
    id: 18,
    name: "Fare Share Food Bank Oakville",
    type: "Food bank",
    neighborhood: "Oakville",
    city: "Oakville",
    address: "1240 Speers Rd, Oakville",
    contact: {
      website: "https://www.oakvillefoodbank.com/",
      note: "Confirm intake, pickup hours, and Oakville service area before visiting.",
    },
    fallbackDistanceKm: 24.8,
    tags: ["groceries", "family", "vegetarian"],
    requirements: ["Service area may apply", "Confirm current food bank hours"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh food referrals", "Family hampers"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "15:00" }],
    geo: { lat: 43.4296, lng: -79.7054 },
  },
  {
    id: 19,
    name: "Muslim Welfare Centre Mississauga Food Bank",
    type: "Food bank",
    neighborhood: "Mississauga",
    city: "Mississauga",
    address: "Mississauga",
    contact: {
      website: "https://mwcanada.org/",
      note: "Confirm the Mississauga food bank location, intake, and current distribution times before visiting.",
    },
    fallbackDistanceKm: 14.2,
    tags: ["groceries", "family", "halal", "newcomer"],
    requirements: ["Confirm current location and intake requirements", "Distribution times may vary"],
    languages: ["English", "Urdu", "Arabic"],
    supplies: ["Groceries", "Halal food support", "Family support"],
    serviceWindows: [{ days: weekday, start: "10:00", end: "16:00" }],
    geo: { lat: 43.589, lng: -79.6441 },
  },
  {
    id: 20,
    name: "Caledon Community Services The Exchange Food Support",
    type: "Food bank",
    neighborhood: "Bolton",
    city: "Caledon",
    address: "55 Healey Rd, Bolton",
    contact: {
      website: "https://ccs4u.org/",
      note: "Confirm Food Support+ intake, schedule, and Caledon service area before visiting.",
    },
    fallbackDistanceKm: 27.7,
    tags: ["groceries", "family", "newcomer"],
    requirements: ["Service area may apply", "Confirm appointment or intake process"],
    languages: ["English"],
    supplies: ["Groceries", "Community referrals", "Family support"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "16:30" }],
    geo: { lat: 43.8588, lng: -79.7116 },
  },
  {
    id: 21,
    name: "Sakeenah Canada Brampton Food Support",
    type: "Family support",
    neighborhood: "Brampton",
    city: "Brampton",
    address: "Brampton",
    contact: {
      website: "https://sakeenahcanada.com/",
      note: "Confirm Brampton food support, eligibility, and current service details before visiting.",
    },
    fallbackDistanceKm: 5.5,
    tags: ["groceries", "family", "halal", "newcomer"],
    requirements: ["Eligibility may vary by program", "Confirm location before travelling"],
    languages: ["English"],
    supplies: ["Food support", "Family support", "Community referrals"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "17:00" }],
    geo: { lat: 43.7315, lng: -79.7624 },
  },
  {
    id: 22,
    name: "Salvation Army Khi Community Food Bank",
    type: "Food bank",
    neighborhood: "Milton",
    city: "Milton",
    address: "820 Nipissing Rd, Unit 4, Milton",
    contact: {
      phone: "905-875-1022",
      website: "https://khicommunity.com/family-services",
      email: "Khi.Info@salvationarmy.ca",
      note: "Call before visiting; the food bank may use appointments and service details can change.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "no-id"],
    requirements: ["Call for information or appointment", "Individuals and families in need"],
    languages: ["English", "French", "Arabic", "Italian", "Portuguese", "Punjabi", "Spanish", "Urdu"],
    supplies: ["Food bank", "Family services", "Diaper voucher referrals"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "14:00" }],
    geo: { lat: 43.5221, lng: -79.8642 },
  },
  {
    id: 23,
    name: "Milton Halal Food Bank",
    type: "Food bank",
    neighborhood: "Milton",
    city: "Milton",
    address: "50 Steeles Ave E, Unit 203, Milton",
    contact: {
      phone: "647-470-3499",
      email: "ayshacentre@gmail.com",
      website: "https://www.211ontario.ca/service/94376793/agency/syyidah-aysha-centre-milton-halal-food-bank/",
      note: "Confirm current hours and intake before visiting.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "halal", "family", "newcomer"],
    requirements: ["Confirm current service hours", "Ask about intake requirements"],
    languages: ["English"],
    supplies: ["Halal groceries", "Food bank support", "Community referrals"],
    geo: { lat: 43.5185, lng: -79.8972 },
  },
  {
    id: 24,
    name: "Milton Community Resource Centre Food for Life",
    type: "Community fridge",
    neighborhood: "Milton",
    city: "Milton",
    address: "410 Bronte St S, Milton",
    contact: {
      phone: "905-635-1106 x225",
      email: "goodfood@foodforlife.ca",
      website: "https://foodforlife.ca/community-program/milton-community-resource-centre/",
      note: "Food for Life lists this as a community food program; registration is done in person on program day.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "vegetarian", "family"],
    requirements: ["Bring one piece of ID showing name and current address", "Bring reusable bags and produce bags"],
    languages: ["English"],
    supplies: ["Fresh fruits and vegetables", "Community fridge", "Food support"],
    serviceWindows: [
      { days: [1], start: "08:30", end: "16:30" },
      { days: [4], start: "08:30", end: "16:30" },
    ],
    geo: { lat: 43.4992, lng: -79.8783 },
  },
  {
    id: 25,
    name: "No One Goes Hungry in Milton",
    type: "Hot meal",
    neighborhood: "Milton",
    city: "Milton",
    address: "121 Chisholm St, Milton",
    contact: {
      website: "https://www.haltonhillsfht.com/FHTfolders.php?df=123&g=1",
      note: "Confirm the current community meal and food program schedule before visiting.",
    },
    fallbackDistanceKm: 0,
    tags: ["hot-meal", "urgent", "family", "vegetarian"],
    requirements: ["Program schedule can vary by site", "Confirm current location before travelling"],
    languages: ["English"],
    supplies: ["Community meals", "Food support", "Frozen meals when available"],
    serviceWindows: [{ days: [0], start: "16:00", end: "18:00" }],
    geo: { lat: 43.5123, lng: -79.8843 },
  },
  {
    id: 26,
    name: "Greater Vancouver Food Bank",
    type: "Food bank",
    neighborhood: "Burnaby",
    city: "Burnaby",
    address: "8345 Winston St, Burnaby",
    contact: {
      phone: "604-876-3601",
      email: "reception@foodbank.bc.ca",
      website: "https://foodbank.bc.ca/",
      note: "Call before visiting; Greater Vancouver Food Bank uses registration and multiple distribution locations.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Registration may be required", "Confirm the closest distribution location before visiting"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh food", "Food distribution referrals"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "16:00" }],
    geo: { lat: 49.2493824, lng: -122.9220659 },
  },
  {
    id: 27,
    name: "Calgary Food Bank",
    type: "Food bank",
    neighborhood: "Highfield",
    city: "Calgary",
    address: "5000 11 St SE, Calgary",
    contact: {
      phone: "403-253-2055",
      website: "https://www.calgaryfoodbank.com/",
      note: "Hamper pickup is by appointment; use the food request process before travelling.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "urgent", "vegetarian"],
    requirements: ["Appointment required for hamper pickup", "Confirm intake steps before visiting"],
    languages: ["English"],
    supplies: ["Emergency hampers", "Groceries", "Community referrals"],
    serviceWindows: [
      { days: [1, 2, 3, 4], start: "08:00", end: "19:30" },
      { days: [5], start: "08:00", end: "16:00" },
      { days: [6], start: "08:30", end: "15:00" },
    ],
    geo: { lat: 51.0097033, lng: -114.035993 },
  },
  {
    id: 28,
    name: "Edmonton Food Bank",
    type: "Food bank",
    neighborhood: "Prince Rupert",
    city: "Edmonton",
    address: "11508 120 St NW, Edmonton",
    contact: {
      phone: "780-425-4190",
      website: "https://www.edmontonsfoodbank.com/",
      note: "Call or use online intake to request food support; pickup and delivery options may vary.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "delivery", "vegetarian"],
    requirements: ["Use intake before pickup", "Confirm delivery or pickup options"],
    languages: ["English"],
    supplies: ["Food hampers", "Groceries", "Community referrals"],
    serviceWindows: [{ days: weekday, start: "08:30", end: "16:00" }],
    geo: { lat: 53.566535, lng: -113.5302222 },
  },
  {
    id: 29,
    name: "Saskatoon Food Bank and Learning Centre",
    type: "Food bank",
    neighborhood: "Riversdale",
    city: "Saskatoon",
    address: "202 Avenue C S, Saskatoon",
    contact: {
      phone: "306-664-6565",
      website: "https://saskatoonfoodbank.org/",
      note: "Confirm current hamper access, learning centre services, and intake details before visiting.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Confirm intake details", "Bring ID if available"],
    languages: ["English"],
    supplies: ["Emergency food hampers", "Fresh food", "Learning centre referrals"],
    serviceWindows: [{ days: weekday, start: "08:00", end: "16:00" }],
    geo: { lat: 52.1274399, lng: -106.6730143 },
  },
  {
    id: 30,
    name: "Regina Food Bank",
    type: "Food bank",
    neighborhood: "Eastview",
    city: "Regina",
    address: "445 Winnipeg St, Regina",
    contact: {
      email: "info@reginafoodbank.ca",
      website: "https://www.reginafoodbank.ca/",
      note: "Confirm current intake, service model, and pickup details before visiting.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Confirm intake requirements", "Proof of address or ID may be requested"],
    languages: ["English"],
    supplies: ["Groceries", "Food hampers", "Community food support"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "16:00" }],
    geo: { lat: 50.4713771, lng: -104.5937209 },
  },
  {
    id: 31,
    name: "Harvest Manitoba",
    type: "Food bank",
    neighborhood: "West End",
    city: "Winnipeg",
    address: "1085 Winnipeg Ave, Winnipeg",
    contact: {
      phone: "204-982-3660",
      website: "https://www.harvestmanitoba.ca/",
      note: "Harvest Manitoba books clients into food banks across Manitoba; call or register before pickup.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Book an appointment before pickup", "Manitoba Health Card or ID may be requested"],
    languages: ["English"],
    supplies: ["Food hampers", "Groceries", "Province-wide referrals"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "15:00" }],
    geo: { lat: 49.9073135, lng: -97.1740053 },
  },
  {
    id: 32,
    name: "Ottawa Food Bank",
    type: "Food bank",
    neighborhood: "Alta Vista",
    city: "Ottawa",
    address: "2001 Bantree St, Ottawa",
    contact: {
      phone: "613-745-7001",
      email: "foodbank@ottawafoodbank.ca",
      website: "https://www.ottawafoodbank.ca/",
      note: "Use the Ottawa Food Bank lookup tool or call to find the right community food program.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Use local lookup or call before visiting", "Community program rules may vary"],
    languages: ["English", "French"],
    supplies: ["Food bank referrals", "Groceries", "Community food programs"],
    serviceWindows: [{ days: weekday, start: "08:00", end: "16:00" }],
    geo: { lat: 45.4060023, lng: -75.6171735 },
  },
  {
    id: 33,
    name: "Moisson Montreal",
    type: "Food bank",
    neighborhood: "Saint-Laurent",
    city: "Montreal",
    address: "6880 Chemin de la Cote-de-Liesse, Montreal",
    contact: {
      phone: "514-344-4494",
      email: "info@moissonmontreal.org",
      website: "https://www.moissonmontreal.org/en/",
      note: "Regional food bank network. Contact them or use 211 Quebec to find the right local food aid organization.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["May refer to partner organizations instead of direct pickup", "Confirm access before visiting"],
    languages: ["French", "English"],
    supplies: ["Food aid referrals", "Regional food distribution", "Community organization support"],
    serviceWindows: [
      { days: [1, 2, 3, 4], start: "07:00", end: "15:45" },
      { days: [5], start: "07:00", end: "12:00" },
    ],
    geo: { lat: 45.4810814, lng: -73.6945069 },
  },
  {
    id: 34,
    name: "Moisson Quebec",
    type: "Food bank",
    neighborhood: "Sainte-Foy",
    city: "Quebec City",
    address: "2909 avenue Kepler, Quebec City",
    contact: {
      phone: "418-682-5061",
      email: "info@moissonquebec.com",
      website: "https://moissonquebec.com/",
      note: "Regional food bank network. Call for help finding a nearby food aid organization.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["May refer to a partner food aid organization", "Confirm local access before visiting"],
    languages: ["French", "English"],
    supplies: ["Food aid referrals", "Regional food distribution", "Community organization support"],
    serviceWindows: [{ days: weekday, start: "08:00", end: "16:00" }],
    geo: { lat: 46.7865419, lng: -71.3141993 },
  },
  {
    id: 35,
    name: "Feed Nova Scotia",
    type: "Food bank",
    neighborhood: "Dartmouth",
    city: "Dartmouth",
    address: "67 Wright Ave, Dartmouth",
    contact: {
      phone: "902-457-1900",
      email: "communications@feednovascotia.ca",
      website: "https://www.feednovascotia.ca/",
      note: "Call or check Feed Nova Scotia for food bank and meal program referrals across the province.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Confirm nearest agency or program", "Partner agency rules may vary"],
    languages: ["English"],
    supplies: ["Food bank referrals", "Groceries", "Meal program referrals"],
    serviceWindows: [{ days: weekday, start: "08:00", end: "16:30" }],
    geo: { lat: 44.7037091, lng: -63.5997121 },
  },
  {
    id: 36,
    name: "Greener Village Fredericton Food Bank",
    type: "Food bank",
    neighborhood: "Barker's Point",
    city: "Fredericton",
    address: "686 Riverside Dr, Fredericton",
    contact: {
      phone: "506-459-7461",
      email: "info@greenervillage.ca",
      website: "https://www.greenervillage.ca/",
      note: "Confirm registration, monthly visit rules, and food bank hours before visiting.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "urgent", "vegetarian"],
    requirements: ["Bring ID and proof of address if available", "Confirm monthly visit rules"],
    languages: ["English"],
    supplies: ["Food bank", "Fresh food", "Clothing and community referrals"],
    serviceWindows: [{ days: [1, 2, 3, 4], start: "09:00", end: "15:00" }],
    geo: { lat: 45.9356615, lng: -66.6094702 },
  },
  {
    id: 37,
    name: "Upper Room Food Bank",
    type: "Food bank",
    neighborhood: "Downtown Charlottetown",
    city: "Charlottetown",
    address: "33 Belmont St, Charlottetown",
    contact: {
      phone: "902-892-7092",
      website: "https://www.urhm.org/",
      note: "Upper Room operates food bank and soup kitchen services; confirm current hours before visiting.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "hot-meal", "urgent", "family"],
    requirements: ["Confirm current food bank and soup kitchen hours", "Ask about intake requirements"],
    languages: ["English"],
    supplies: ["Food bank", "Soup kitchen", "Prepared meals"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "15:00" }],
    geo: { lat: 46.2448535, lng: -63.1215351 },
  },
  {
    id: 38,
    name: "Community Food Sharing Association",
    type: "Food bank",
    neighborhood: "St. John's",
    city: "St. John's",
    address: "21 Mews Place, St. John's",
    contact: {
      phone: "709-722-0130",
      email: "cfsa@nl.rogers.com",
      website: "http://www.cfsa.nf.net/",
      note: "Provincial food bank association. Call to confirm the closest member food bank or distribution option.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["May refer to member food banks", "Confirm local access before visiting"],
    languages: ["English"],
    supplies: ["Food bank referrals", "Regional food distribution", "Groceries"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "16:00" }],
    geo: { lat: 47.5594079, lng: -52.772657 },
  },
  {
    id: 39,
    name: "Food Bank Society of the Yukon",
    type: "Food bank",
    neighborhood: "Downtown Whitehorse",
    city: "Whitehorse",
    address: "306B Alexander St, Whitehorse",
    contact: {
      phone: "867-393-2265",
      website: "https://www.whitehorsefoodbank.ca/",
      note: "Emergency food support for Whitehorse and Yukon communities; confirm current hours before visiting.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "urgent", "vegetarian"],
    requirements: ["Confirm current service hours", "Ask about community access and ID requirements"],
    languages: ["English"],
    supplies: ["Emergency food", "Food hampers", "Community referrals"],
    serviceWindows: [{ days: weekday, start: "10:00", end: "14:00" }],
    geo: { lat: 60.7223998, lng: -135.0610475 },
  },
  {
    id: 40,
    name: "Yellowknife Food Bank",
    type: "Food bank",
    neighborhood: "Downtown Yellowknife",
    city: "Yellowknife",
    address: "4909 50th St, Yellowknife",
    contact: {
      phone: "867-873-4035",
      note: "Call ahead to confirm the current food bank location, hours, and intake process.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "urgent", "vegetarian"],
    requirements: ["Call ahead before visiting", "Hours and location details can change"],
    languages: ["English"],
    supplies: ["Food bank", "Emergency food", "Community referrals"],
    serviceWindows: [{ days: weekday, start: "10:00", end: "15:00" }],
    geo: { lat: 62.454954, lng: -114.3731066 },
  },
  {
    id: 41,
    name: "Qajuqturvik Community Food Centre",
    type: "Hot meal",
    neighborhood: "Iqaluit",
    city: "Iqaluit",
    address: "655 Mattaaq Crescent, Iqaluit",
    contact: {
      phone: "867-979-4863",
      email: "info@qajuqturvik.ca",
      website: "https://qajuqturvik.ca/en",
      note: "Community food centre with meals and food programs. Confirm current program schedule before visiting.",
    },
    fallbackDistanceKm: 0,
    tags: ["hot-meal", "groceries", "urgent", "family"],
    requirements: ["Confirm current program schedule", "Ask about food program access"],
    languages: ["English", "Inuktitut"],
    supplies: ["Community meals", "Food programs", "Food skills support"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "16:00" }],
    geo: { lat: 63.7479425, lng: -68.5171677 },
  },
  {
    id: 42,
    name: "Central Okanagan Food Bank",
    type: "Food bank",
    neighborhood: "Enterprise",
    city: "Kelowna",
    address: "2310 Enterprise Way, Kelowna",
    contact: {
      phone: "250-763-7161",
      website: "https://cofoodbank.com/",
      note: "Confirm client registration, pickup location, and current hours before visiting.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Registration may be required", "Confirm pickup details before travelling"],
    languages: ["English"],
    supplies: ["Food hampers", "Groceries", "Fresh food"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "15:30" }],
    geo: { lat: 49.8835858, lng: -119.4346914 },
  },
  {
    id: 43,
    name: "London Food Bank",
    type: "Food bank",
    neighborhood: "Glen Cairn",
    city: "London",
    address: "926 Leathorne St, London",
    contact: {
      website: "https://www.londonfoodbank.ca/",
      note: "Confirm current client hours, intake, and pickup details before visiting.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "urgent", "vegetarian"],
    requirements: ["Confirm client hours before visiting", "Bring ID if available"],
    languages: ["English"],
    supplies: ["Emergency food", "Groceries", "Community referrals"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "16:00" }],
    geo: { lat: 42.961589, lng: -81.2165712 },
  },
  {
    id: 44,
    name: "The Food Bank of Waterloo Region",
    type: "Food bank",
    neighborhood: "Alpine",
    city: "Kitchener",
    address: "50 Alpine Court, Kitchener",
    contact: {
      phone: "519-743-5576",
      website: "https://www.thefoodbank.ca/",
      note: "Regional food distribution hub. Use local agency referrals for direct food support.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["May refer through partner agencies", "Confirm direct access before visiting"],
    languages: ["English"],
    supplies: ["Food aid referrals", "Regional food distribution", "Community agency support"],
    serviceWindows: [{ days: weekday, start: "08:30", end: "16:30" }],
    geo: { lat: 43.4243671, lng: -80.4781783 },
  },
  {
    id: 45,
    name: "Guelph Food Bank",
    type: "Food bank",
    neighborhood: "The Junction",
    city: "Guelph",
    address: "100 Crimea St, Guelph",
    contact: {
      phone: "519-767-1380",
      website: "https://guelphfoodbank.ca/",
      note: "Confirm current food bank hours and intake details before visiting.",
    },
    fallbackDistanceKm: 0,
    tags: ["groceries", "family", "urgent", "vegetarian"],
    requirements: ["Confirm current hours before visiting", "Ask about ID or proof of address requirements"],
    languages: ["English"],
    supplies: ["Food bank", "Groceries", "Community referrals"],
    serviceWindows: [{ days: weekday, start: "09:00", end: "15:00" }],
    geo: { lat: 43.5368528, lng: -80.2625138 },
  },
];

export const needOptions = [
  { id: "groceries", label: "Groceries" },
  { id: "hot-meal", label: "Hot meal" },
  { id: "urgent", label: "Need today" },
  { id: "no-id", label: "No ID" },
  { id: "halal", label: "Halal" },
  { id: "vegetarian", label: "Vegetarian" },
  { id: "baby", label: "Baby supplies" },
  { id: "delivery", label: "Delivery" },
  { id: "student", label: "Student" },
  { id: "family", label: "Family" },
  { id: "newcomer", label: "Newcomer" },
];
