export type Resource = {
  id: number;
  name: string;
  type: "Food bank" | "Hot meal" | "Community fridge" | "Student support" | "Family support";
  neighborhood: string;
  city: string;
  address: string;
  openNow: boolean;
  nextWindow: string;
  phone: string;
  fallbackDistanceKm: number;
  tags: string[];
  requirements: string[];
  languages: string[];
  supplies: string[];
  geo: {
    lat: number;
    lng: number;
  };
};

export const resources: Resource[] = [
  {
    id: 1,
    name: "Davis Campus Food Shelf",
    type: "Student support",
    neighborhood: "Sheridan Davis",
    city: "Brampton",
    address: "7899 McLaughlin Rd, Brampton",
    openNow: true,
    nextWindow: "Open until 6:00 PM",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 0.8,
    tags: ["student", "groceries", "no-id", "halal", "vegetarian"],
    requirements: ["Student-focused support", "Confirm campus access before visiting"],
    languages: ["English", "Punjabi", "Urdu"],
    supplies: ["Pantry staples", "Rice", "Lentils", "Hygiene kits"],
    geo: { lat: 43.7302, lng: -79.7325 },
  },
  {
    id: 2,
    name: "Regeneration Outreach",
    type: "Hot meal",
    neighborhood: "Downtown Brampton",
    city: "Brampton",
    address: "156 Main St N, Brampton",
    openNow: true,
    nextWindow: "Meal program hours vary by day",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 2.4,
    tags: ["hot-meal", "urgent", "no-id", "wheelchair", "vegetarian"],
    requirements: ["Walk-in services may be available", "Confirm service window before visiting"],
    languages: ["English"],
    supplies: ["Hot meals", "Drop-in support", "Community referrals"],
    geo: { lat: 43.6918, lng: -79.7641 },
  },
  {
    id: 3,
    name: "Food Banks Mississauga",
    type: "Food bank",
    neighborhood: "East Mississauga",
    city: "Mississauga",
    address: "3121 Universal Dr, Mississauga",
    openNow: false,
    nextWindow: "Referral and pickup times vary",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 4.7,
    tags: ["groceries", "family", "delivery", "vegetarian", "newcomer"],
    requirements: ["Use local intake process", "Confirm closest pickup location"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh food referrals", "Family support"],
    geo: { lat: 43.6379, lng: -79.6416 },
  },
  {
    id: 4,
    name: "Eden Food for Change",
    type: "Food bank",
    neighborhood: "Meadowvale",
    city: "Mississauga",
    address: "3185 Unity Dr, Mississauga",
    openNow: false,
    nextWindow: "Program hours vary",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 7.8,
    tags: ["groceries", "family", "vegetarian", "newcomer"],
    requirements: ["Registration may be required", "Confirm eligibility before visiting"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh produce", "Community referrals"],
    geo: { lat: 43.5787, lng: -79.7575 },
  },
  {
    id: 5,
    name: "Daily Bread Food Bank",
    type: "Food bank",
    neighborhood: "Etobicoke",
    city: "Toronto",
    address: "191 New Toronto St, Toronto",
    openNow: false,
    nextWindow: "Member food bank hours vary",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 18.1,
    tags: ["groceries", "family", "delivery", "vegetarian", "no-id"],
    requirements: ["Use locator or call ahead", "Bring ID if available, but ask about no-ID options"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh produce", "Member agency referrals"],
    geo: { lat: 43.6005, lng: -79.5057 },
  },
  {
    id: 6,
    name: "Fort York Food Bank",
    type: "Food bank",
    neighborhood: "Trinity Bellwoods",
    city: "Toronto",
    address: "797 Dundas St W, Toronto",
    openNow: true,
    nextWindow: "Drop-in windows vary",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 25.5,
    tags: ["groceries", "hot-meal", "urgent", "no-id", "vegetarian"],
    requirements: ["Walk-in support may be available", "Confirm hours before visiting"],
    languages: ["English"],
    supplies: ["Groceries", "Meals", "Clothing and referrals"],
    geo: { lat: 43.6519, lng: -79.4093 },
  },
  {
    id: 7,
    name: "North York Harvest Food Bank",
    type: "Food bank",
    neighborhood: "Amesbury",
    city: "Toronto",
    address: "116 Industry St, Toronto",
    openNow: false,
    nextWindow: "Network agency hours vary",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 23.4,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Use agency referral or call ahead", "Service area may apply"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh food", "Community referrals"],
    geo: { lat: 43.7009, lng: -79.4899 },
  },
  {
    id: 8,
    name: "Feed Scarborough",
    type: "Food bank",
    neighborhood: "Scarborough",
    city: "Toronto",
    address: "Scarborough, Toronto",
    openNow: true,
    nextWindow: "Multiple program windows across Scarborough",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 42.2,
    tags: ["groceries", "family", "halal", "vegetarian", "newcomer"],
    requirements: ["Confirm nearest program location", "Service times vary by site"],
    languages: ["English"],
    supplies: ["Groceries", "Culturally appropriate food", "Prepared meals"],
    geo: { lat: 43.7764, lng: -79.2318 },
  },
  {
    id: 9,
    name: "Richmond Hill Community Food Bank",
    type: "Food bank",
    neighborhood: "Richmond Hill",
    city: "Richmond Hill",
    address: "55 Newkirk Rd, Richmond Hill",
    openNow: false,
    nextWindow: "Pickup hours vary",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 36.9,
    tags: ["groceries", "family", "newcomer", "vegetarian"],
    requirements: ["Registration may be required", "Confirm catchment area"],
    languages: ["English"],
    supplies: ["Groceries", "Fresh produce", "Household staples"],
    geo: { lat: 43.8752, lng: -79.4232 },
  },
  {
    id: 10,
    name: "Vaughan Food Bank",
    type: "Food bank",
    neighborhood: "Concord",
    city: "Vaughan",
    address: "71 Marycroft Ave, Vaughan",
    openNow: false,
    nextWindow: "Distribution windows vary",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 29.6,
    tags: ["groceries", "family", "vegetarian"],
    requirements: ["Call ahead for current pickup process", "Service area may apply"],
    languages: ["English"],
    supplies: ["Groceries", "Family hampers", "Community referrals"],
    geo: { lat: 43.7856, lng: -79.5617 },
  },
  {
    id: 11,
    name: "The Stop Community Food Centre",
    type: "Hot meal",
    neighborhood: "Davenport",
    city: "Toronto",
    address: "1884 Davenport Rd, Toronto",
    openNow: true,
    nextWindow: "Meal and drop-in programs vary",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 27.5,
    tags: ["hot-meal", "urgent", "no-id", "vegetarian"],
    requirements: ["Drop-in programs may be available", "Confirm schedule before visiting"],
    languages: ["English"],
    supplies: ["Meals", "Community kitchen", "Food access referrals"],
    geo: { lat: 43.6716, lng: -79.4521 },
  },
  {
    id: 12,
    name: "Feed the Need in Durham",
    type: "Food bank",
    neighborhood: "Oshawa",
    city: "Durham Region",
    address: "371 Marwood Dr, Oshawa",
    openNow: false,
    nextWindow: "Partner agency hours vary",
    phone: "Call 211 for current intake details",
    fallbackDistanceKm: 71.2,
    tags: ["groceries", "family", "delivery", "vegetarian"],
    requirements: ["Use partner agency intake", "Confirm nearest Durham pickup site"],
    languages: ["English"],
    supplies: ["Groceries", "Regional partner referrals", "Family hampers"],
    geo: { lat: 43.8792, lng: -78.8795 },
  },
];

export const needOptions = [
  { id: "groceries", label: "Groceries" },
  { id: "hot-meal", label: "Hot meal" },
  { id: "urgent", label: "Need today" },
  { id: "no-id", label: "No ID" },
  { id: "halal", label: "Halal" },
  { id: "vegetarian", label: "Vegetarian" },
  { id: "baby", label: "Baby supplies" },
  { id: "delivery", label: "Delivery" },
  { id: "student", label: "Student" },
  { id: "family", label: "Family" },
  { id: "newcomer", label: "Newcomer" },
];
